name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: dvc_cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Get DVC 1.0 
          apt-get --purge remove -y dvc
          pip install "git+https://github.com/iterative/dvc#egg=dvc[s3]"
          dvc --version
          git fetch --prune --unshallow
          
          pip install -r requirements.txt
          
          # Pull dataset with DVC 
          dvc pull
          
          # Reproduce pipeline if any changes detected in dependencies
          dvc repro train.dvc
          
          # Use DVC metrics diff to compare metrics to previous commit
          BASELINE=master
          dvc metrics diff --show-md "$BASELINE" >> report.md
          
          # Add figure to report
          echo "\n" >> report.md
          cml-publish pr_curve.png --md --title 'pr curve' >> report.md
          cml-send-github-check report.md 
          
          
