name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: dvc_cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip3 install -r requirements.txt
          
          # Pull dataset with DVC 
          dvc pull
          
          # Reproduce pipeline if any changes detected in dependencies
          dvc repro train.dvc
          
          # Use DVC metrics diff to compare metrics to previous commit
          BASELINE=origin/master
          dvc metrics diff --show-json "$BASELINE" | cml-metrics >> report.md
          
          # Add figure to report
          cml-publish pr_curve.png --md --title 'pr curve' >> report.md
          cml-send-github-check report.md 
          
          
